// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"model_mall_backend/backend/internal/middleware"
	"model_mall_backend/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 全局中间件
	server.Use(middleware.NewRequestMiddleware().Handle)
	server.Use(middleware.NewResponseMiddleware().Handle)

	// 公开路由（不需要认证）
	server.AddRoutes([]rest.Route{
		//{
		//	Method:  http.MethodPost,
		//	Path:    "/api/login",
		//	Handler: LoginHandler(serverCtx),
		//},
		//{
		//	Method:  http.MethodPost,
		//	Path:    "/api/register",
		//	Handler: RegisterHandler(serverCtx),
		//},
		
		// 模型服务回调接口（公开）
		{
			Method:  http.MethodPost,
			Path:    "/api/model/callback",
			Handler: ModelCallbackHandler(serverCtx),
		},
	})

	// 需要认证的路由
	server.AddRoutes(
		[]rest.Route{
			//{
			//	Method:  http.MethodGet,
			//	Path:    "/api/user/info",
			//	Handler: GetUserInfoHandler(serverCtx),
			//},
			
			// 图片相关接口
			{
				Method:  http.MethodPost,
				Path:    "/api/images/upload",
				Handler: UploadImageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/images",
				Handler: GetImageListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/images/:image_id/labels",
				Handler: GetImageLabelsHandler(serverCtx),
			},
			
			// 识别任务相关接口
			{
				Method:  http.MethodGet,
				Path:    "/api/tasks/:task_id/status",
				Handler: GetTaskStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/tasks",
				Handler: GetTaskListHandler(serverCtx),
			},
		}, rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
